baseurl = "/" # Hostname (and path) to the root.
title = "Daniel Roelfs" # Site title.
theme = "hugo-coder-portfolio-edit" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.
defaultContentLanguageInSubdir = true
GoogleAnalytics = "UA-26694895-2"
publishDir = "docs"

paginate = 20 # Default number of pages per page in pagination.

PygmentsStyle = "monokai" # Color-theme or style for syntax highlighting.
PygmentsCodeFences = true # Enable code fence background highlighting.
PygmentsCodeFencesGuessSyntax = false # Enable syntax guessing for code fences without specified language.
PygmentsUseClasses = true # new add

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "index\\.html", "about\\.html", "static/blog/\\*_files/", "README"] 

[markup]
  defaultMarkdownHandler = "blackfriday"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params] # theme parameters
    author = "Daniel Roelfs" # Author's name.
    info = "PhD Candidate in Brain Imaging & Genetics" # Author's job title or info.
    description = "Daniel Roelfs' personal website" # Site description.
    keywords = "blog,personal,coding" # Site keywords.
    avatarurl = "images/avatar.png" # Contain the path of the optional avatar in the static folder.

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = true

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    # Bottom sns share
    snsShare = true # new add
    # Popular sns share
    # if you want add sns. please message!
    enableTwitterShare = false  # new add
    enableFacebookShare = false # new add
    enableHatenaShare = false   # new add
    enableLineShare = false     # new add
    enableLinkedInShare = false # new add

    thumbnail = "images/tn.png" # default sns thumbnail
    
# Social links
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 1
    url = "https://twitter.com/dthroelfs/"
[[params.social]]
    name = "GitHub"
    icon = "fab fa-github"
    weight = 2
    url = "https://github.com/danielroelfs/"
[[params.social]]
    name = "ORCID"
    icon = "fab fa-orcid"
    weight = 3
    url = "https://orcid.org/0000-0002-1083-002X"
[[params.social]]
    name = "Google Scholar"
    icon = "fas fa-graduation-cap"
    weight = 4
    url = "https://scholar.google.com/citations?user=QmVQcsAAAAAJ&hl=en"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 5
    url = "https://www.linkedin.com/in/danielroelfs/"
[[params.social]]
    name = "Mail"
    icon = "fas fa-envelope"
    weight = 6
    url = "mailto:daniel.roelfs@medisin.uio.no"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "blog"
[[menu.main]]
    name = "Photography"
    weight = 2
    url = "photography"    
[[menu.main]]
    name = "Publications"
    weight = 3
    url = "publications"
[[menu.main]]
    name = "Curriculum Vitæ"
    weight = 4
    url = "cv"
[[menu.main]]
    name = "About"
    weight = 5
    url = "about"